### ISSUE TITLE
Document the API

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispersservices#236]
Creating a ticket for this so that we have a record of what was done and what was found.

I wrote short descriptions for the parameters using the WHISPers Business rules sheet when I could. It should probably still be reviewed by one of you since I don't really know what some of them are for (e.g. circles?).

There is still the issues that Aaron identified with #1 being `list` and `read` actions only showing the class property settings. And #2 being unable to put a description next to the endpoint name 
![image](https://user-images.githubusercontent.com/23640741/56365318-8dab3900-61be-11e9-8f68-ce78f54deac7.png)

I spent some time trying to figure out #2 but came up with nothing as well. Issue created for #1 https://github.com/USGS-WiM/whispersservices_django/issues/235

**Comment by aaronstephenson** [comment]
Good news everyone! [DRF 3.11](https://www.django-rest-framework.org/community/3.11-announcement/) (released December 12, 2019) now populates the OpenAPI path operation `description` field for each endpoint, so there's likely no need for the monkey patch I mentioned [previously](https://github.com/USGS-WiM/whispersservices_django/issues/236#issuecomment-521474592):
>Porting of the old CoreAPI parsing of docstrings to form OpenAPI operation descriptions.

Here's what the swagger docs looks like now:
![image](https://user-images.githubusercontent.com/8713712/76440793-620fdf00-638c-11ea-8e2a-ce1dd3519aee.png)


Still missing the OpenAPI path `summary` tho (the empty red annotation above). Not sure what to do about that, because the operation description is coming from the docstring. I'll keep looking into this.

**Comment by aaronstephenson** [comment]
Implemented with upgrade to Django REST Framework v3.12 and use of OpenAPI 3 in 2.0.0 3111f67
