### ISSUE TITLE
Event sharing getting only read access

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#267]
Partner collaborator only getting read access despite showing write access:
From Bob at NWHC:
"Whispers 200122. I added Robb as a collaborator with Read and Write Access (and that is what shows when I go and look at it now but he says in his email he only has read access).  Any thoughts on what is going on?"

From Robb at USFWS:
"I logged into the WHISPers and viewed event # 200122; however, I appear to only have permission to READ (and cannot edit)."

**Comment by JChipault** [comment]
@BlakeDraper I can see 200104 on the live site when i log in, but it's marked as not public, so maybe that's why you can't see it?

**Comment by JChipault** [comment]
I tried making 200104 public and being a read/write collaborator as testpartner (the account I created that's paired with Abilene Zoo as org) and I still only see the public data.

Then I thought maybe I should just try a more current event because 200104 is a wonky event that needs to be deleted anyway... but I had same issue with 200168 on the prod site. I signed in as jchipault and made my testpartner account (Abilene Zoo account linked to my personal email address) as a read/write collaborator on event 200168. Then I signed in as testpartner and checked my dashboard to make sure I was listed as a collaborator:

![image](https://user-images.githubusercontent.com/49287076/63130324-a74b6a00-bf7f-11e9-834c-dcc1622dda44.png)

but then when I go to that event, I only see the public data
![image](https://user-images.githubusercontent.com/49287076/63130541-6bfd6b00-bf80-11e9-968c-f7039e0bc2c6.png)

I log out and log back in as jchipault and see that the abilene zoo account is still listed as a collaborator.
![image](https://user-images.githubusercontent.com/49287076/63130612-a6ff9e80-bf80-11e9-938e-f059b907f503.png)

**Comment by JChipault** [comment]
I've been using firefox but I also checked 200104 on chrome

**Comment by JChipault** [comment]
because it's the production site, i'm going to remove testpartner from 200168 now so that people don't get confused as to why there's suddenly abilene zoo involved in a live event ;)

**Comment by BlakeDraper** [comment]
Strange. I have now found 200104 in the prod site/database (I had been logged in as Admin so the public/not public distinction would make no difference). Anyway, I added wimPartnerUser (org Abilene Zoo) as a read/write collaborator while logged in as Admin and then logged in as that user and can see what I need to see. Next I'll try this as a Role 2 which is what jchipault is (Admin instead of SuperAdmin).

**Comment by BlakeDraper** [comment]
@JChipault I remain baffled. I have now tested with creating the collaborator connection using the same role as your account, and the permissions are working.

I did notice a small problem which is unrelated (or at least unconnected) - the read/write collaborators are not showing in the list when you load the event details page - but that is superficial because the actual event record does have it. I will fix that for a next release. But really I can see that both A) the collaborators list is part of the event details record and B) I am able to see the expected data when testing this using the same roles arrangement you have described. We may need to do an in-person debug session where I sit down with you and to catch what is happening.

**Comment by JChipault** [comment]
yup, weird, just tried it again on production site in chrome and only see public data when I'm logged in as partner. might you be at nwhc for thursday's meeting and we could look at this together then?

**Comment by BlakeDraper** [comment]
Yes let's do it then, on Thursday.

**Comment by JChipault** [comment]
So I tried adding the testpartner account on the live site v 2.4.2 to events 200104 and 200168 as a read/write collaborator and I still only see public data (no privileged data section at all) when I log in as that test account. 
![image](https://user-images.githubusercontent.com/49287076/63603309-0831fe00-c58f-11e9-9211-c06903a45b17.png)
![image](https://user-images.githubusercontent.com/49287076/63603341-1b44ce00-c58f-11e9-88a4-46c4695e9b9c.png)
(I'm now removing this testpartner from 200168 since that's a live event viewable to the public).

**Comment by JChipault** [comment]
Just tried it on the test site v2.4.2 and it's working there. So perhaps there's something wonky in my account settings for live site accounts jchipault and/or testpartner?

**Comment by BlakeDraper** [comment]
@JChipault You were right that it was an account issue - that testpartner account was actually the affiliate role, not a partner role. The client was preventing display of privileged data to Affiliate roles (which I also know is not the correct behavior, and that will be updated in the next patch). So really the issue at hand and the reason for it not working on prod/live but working on test is that improper role assignment for that account. 

We have updated that testpartner account to be the partner role, but now for some EROS reason, we are being blocked from logging into that particular account (but no others). 

So - the issue is fixed, you just can't test it with that particular account yet, until we determine the cause of this login issue.

**Comment by aaronstephenson** [comment]
Hi Jenny, after spending most of the day troubleshooting why we couldn't get that testpartner account to work after changing its role, I just decided to delete it. I recreated it with the same username and password and email, etc. The only difference now is that its ID is 47 instead of 24, and it isn't in any collaborator lists.

So, give that recreated user a test run and let us know how it goes!

**Comment by JChipault** [comment]
@aaronstephenson   yup, it works now. weird. Next, I'll see if Robb Kaler can read/write 200122 from Alaska.

**Comment by aaronstephenson** [comment]
Thanks @JChipault that helped a ton!

I have discovered that the permissions checks are testing permissions against the object being edited. When the object being edited is an event, everything is working as expected. But for child objects like eventlocations, no permissions are being found. So the fix is to just do a check of the object model, and if it is not an event, to then check permissions of the object's parent event.

This is a quick and easy fix.

**Comment by aaronstephenson** [comment]
Fixed in 1.2.0 f9037d4

**Comment by aaronstephenson** [comment]
@JChipault The updated code is now live in test and prod.

**Comment by JChipault** [comment]
@aaronstephenson ok, I emailed Robb in Alaska again to see if he could check it out.

**Comment by JChipault** [comment]
From Robb: 
Yah! Regarding Event 200122, I successfully (1) edited the Event End Date, (2) edited Species Details (MEGU death due to emaciation; ARTE death due to Toxicosis, and (3) change the WHISPers record status from Incomplete, to Complete, and back to Incomplete.

Pretty dang functional! 

My compliments to the chefs!
