### ISSUE TITLE
server error 500 when adding a new location

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#272]
epi staff (Anne Ballmann) was trying to add a 4th location to event 200136 from event details page and was getting the server error 500 toast message after she hit submit. No new locations showed up. Then Jenny went to troubleshoot with her and asked her to hit refresh on her browser and then she had four entries of that 4th location (probably one entry for every time she hit submit and got the error message).

**Comment by JChipault** [comment]
@aaronstephenson similar thing happening with v2.7.1. event 170785. I'm NOT getting error messages (phew!) but when I add a species diagnosis, I get a toast message saying that it was added but then it doesn't show up on my form until I manually refresh my browser. Only happening intermittently though (of course). Had it happen ~4 times in a row and then it started working fine (fine in that the page would refresh automatically when I committed a new species dx). Maybe not worth spending a lot of time tracking down yet, but wanted to alert you in case it was a fast fix. I can keep an eye on it and let you know if it creeps up again.

**Comment by aaronstephenson** [comment]
@JChipault if the object appears when you refresh your browser, that sounds like a front end issue.

One way you could confirm whether or not this is not a back end problem is to check the browsable API right after you create a new species diagnosis to see if the new object exists...

by looking at the end of the Species Diagosis list:
https://whisperstest.wim.usgs.gov/whispersservices/speciesdiagnoses/?page=28

or the `speciesdiagnoses` nested object of Event Details of the parent event:
https://whisperstest.wim.usgs.gov/whispersservices/eventdetails/170785/

(don't log in to the browsable API (public data is viewable by anyone) while you are logged in to the whispers client, though, because of the known CSRF problem)
