### ISSUE TITLE
collaborator can't delete

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#375]
In testing the notifications today I noticed that when in the event details interface the abilenetest user can't delete most fields in 170872, on which they are a read/write collaborator. I couldn't even delete a species that I had just added when logged in as abilenetest.

I'm hopeful that it's just some recent change that accidentally affected this permissions and therefore maybe an easy flip back to the previous status???

**Comment by aaronstephenson** [comment]
This is not a bug but a deliberate decision and it was not introduced recently; it has been this way for quite a long time. Delete is distinct from update. Currently only super_admin, admin, or the object's creator or a manager or admin in the object creator's organization can delete events or event child objects.

Changing this behavior would not be difficult, but I need to discuss it with @BlakeDraper

**Comment by BlakeDraper** [comment]
@JChipault Just seconding Aaron on this one - this was a design decision made some time ago with the WHISPers team, though I don't remember exactly when. I believe the conclusion was that deletion of a record is a pretty serious action (tracked in the history tables, but otherwise gone into the ether) and that it should not be available to a collaborator. If the thinking has changed on that, we'd like to chalk that up as a future development/enhancement since it is not a bug.

**Comment by nbaertlein** [comment]
@BlakeDraper @aaronstephenson I remember discussing this as well.  We'll let this marinate with users for awhile before we proceed with any changes to the current code.
