### ISSUE TITLE
Small issue in event collaborators update logic - probably feature, not bug

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#407]
![image](https://user-images.githubusercontent.com/6978380/95110282-64100580-0703-11eb-98b0-ae79a4d53da1.png)

You can see here, one of the collaborators (users) is being dropped on this update. What I think may be happening here is an email address filtering. 

ID 3 has the email address `nbaertlein+1@usgs.gov`
and ID 4 has the email address `nbaertlein@usgs.gov`

Since only 4 is sticking, seems it is overwriting 3 when you are filtering for unique? Must be ignoring the `+1`, as an email system would, and treating those as the same. This is the dev DB, so I don't think this would happen much if at all in production, but just looking for confirmation on this behavior.

**Comment by aaronstephenson** [comment]
This is intentional, but the email address itself is immaterial. The logic is written such that if a user is in the 'write' group, it can't also be in the 'read' group (since 'write' includes read ability). In your example, user 3 is already in the 'write' group, and so it is ignored when you include it in the 'read' group update.

**Comment by BlakeDraper** [comment]
Ok thanks. Makes sense obviously - may be confusing for user but that's a UX issue I'll have to figure out (or not).
