### ISSUE TITLE
Events dashboard does not sort in whispersprod.cr

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#411]
Sort functions (i.e. ID, Type, Affected, etc) do not work on ‘Events’ dashboard.

![image](https://user-images.githubusercontent.com/38669574/96274588-4ad64700-0f96-11eb-897e-ed5ed2b79d21.png)

**Comment by BlakeDraper** [comment]
@aaronstephenson there seems to be an issue with the filtering queries. Just one example:
https://whisperstest.cr.usgs.gov/api/eventsummaries/?enddate=2020-10-16&format=json&ordering=affected_count&page=1&page_size=5&startdate=2020-09-18

Although the ordering param is included with the value `affected_count`, the results are not in fact ordered by that field.

**Comment by aaronstephenson** [comment]
Fixed in 2.0.3 fa803d9. Please test to confirm.

**Comment by BlakeDraper** [comment]
Looks good to me.

**Comment by JChipault** [comment]
Sorry that I didn't catch this before, but same issue of the column sort feature not working is happening in these other tabs of the dashboard: Notification (although seems to work after I hit refresh on browser), Event Groups, Contacts, and Circles

**Comment by BlakeDraper** [comment]
@aaronstephenson we do in fact have a failure to properly filter on the following endpoints:
- `/eventgroups` (example: https://whisperstest.cr.usgs.gov/api/eventgroups/?ordering=comment&page=1&page_size=20)
- `/circles` (example: https://whisperstest.cr.usgs.gov/api/circles/?ordering=-users&page=1&page_size=20)

@JChipault I cannot recreate the issue on the Notifications tab. Are you on the test app? There may have been some small fluke. If its still not working, how many notifications do you have? There would be a delay if you have a large number. 

Speaking of large numbers, the Contacts tab is almost certainly responding slowly because of the legacy data contacts issue - over 3k contacts. This is a known issue that we have deferred for the time being.

**Comment by JChipault** [comment]
Good call on contacts... I re-tested using an account that only had 2 contacts and it sorts on every column EXCEPT phone number and email address.

Notifications was kind of spotty for me yesterday. Seems ok today. So maybe just a fluke.

**Comment by aaronstephenson** [comment]
@BlakeDraper in both of those cases you are attempting to sort by nested objects. Is that something we've actually ever allowed? I see no evidence of it in the notifications branch (pre-refactor): https://github.com/USGS-WiM/whispersservices/blob/notifications/whispersservices/views.py

**Comment by aaronstephenson** [comment]
I also looked at sorting for contacts (as admin user, so all 3k+ records), and I was able to order by email address and phone number and get expected results.

**Comment by aaronstephenson** [comment]
Looks like I forgot to put the OrderingFilter in the abstract class that all the views inherit from when I did the refactor. Fixed in 2.0.5 823f533

**Comment by BlakeDraper** [comment]
And @JChipault I spent some time with all the sorts on the User dash and found a few bugs that I squashed, so all of those should be fully functional with the next release.
