### ISSUE TITLE
Update content of service request notification

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#431]
> Source for service response notifications is not source of the response. Case in point https://whispers.usgs.gov/event/200986 Deana is listed as the source of the service request response (i.e. yes/no/maybe), however it should be Barb. I think this source just needs to be updated to point to the username for from the field whispers_servicerequest.response_by_id . I don't think this a reversion, but just something we found now.

**Comment by BlakeDraper** [comment]
@JChipault can you confirm that this is an issue with the notification, not the display on the event details page?

**Comment by JChipault** [comment]
Confirmed. It's the "source" that can be viewed in the dashboard that's off. Here's an example from the test site. User abilenetest can't set a service request response so they shouldn't be the source.
![image](https://user-images.githubusercontent.com/49287076/102807595-8faa9f80-4384-11eb-9902-acff9ab5e7d6.png)

**Comment by aaronstephenson** [comment]
Looking at the example of Event 200986 in the production client, I see this:
![image](https://user-images.githubusercontent.com/8713712/102932394-cf958380-4465-11eb-86ec-51e0ce928f40.png)

Yet when I look at the actual response from the API, I see this:
![image](https://user-images.githubusercontent.com/8713712/102932521-11262e80-4466-11eb-9155-38142a4db8c5.png)

The `response_by` field has a value of 19, which is Barb. So this problem seems like just a front end field mapping mismatch, where the front end is displaying the service request `created_by` information, not `response_by` information.

**Comment by aaronstephenson** [comment]
Oh, I glanced over the big about notifications. I'll look at that.

**Comment by aaronstephenson** [comment]
Ah yep, it was the notification create code, I had `source` set to `modified_by`, not `response_by`.

**Comment by aaronstephenson** [comment]
Fixed deployed in test environment.

**Comment by JChipault** [comment]
I checked it out on the test site and it looks good. Thanks!

**Comment by aaronstephenson** [comment]
Fix deployed in production environment.
