### ISSUE TITLE
Question on ALL Events notification

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#432]
From NWHC:
> Question: are the "All Event" and "Custom" notifications generated based on permissions to an event or are they restricted to public events only? As an admin user, I don't think I'm getting notified when ALL events are created, but only when public events are created.

**Comment by JChipault** [comment]
For example, jchipault user got a "Your Organization Events" notification for 200983 even though it's marked as "not visible to the public" but did NOT get an "All Events" notification for 200981 and 200892, which were events "not visible to the public" created by state partners. As jchipault (WHISPers admin), I have permissions to see these events, but I was not notified about them. 

We think we might be seeing some inconsistencies within the "Custom" notifications along this same lines too and wanted to double-check that those are based on permissions.

**Comment by aaronstephenson** [comment]
Yes, nightly notifications are based on permissions, and yes admins should see all event notifications regardless of source or public/private status if they opt to receive them. I will investigate why admins are not seeing private non-org events.

**Comment by JChipault** [comment]
@aaronstephenson any insight on this one? I think this is the next highest priority bug for me now that you've conquered the add collaborators issue.

**Comment by aaronstephenson** [comment]
Yes, I'm looking at all of these, and this is the next one up.

**Comment by aaronstephenson** [comment]
OK, I had a chance to look into this. To answer the question, there is no bug here, the code is operating as [written](https://github.com/USGS-WiM/whispersservices/blob/master/whispersapi/scheduled_tasks.py#L902):

1. All public events created/edited yesterday (excluding those that changed from private to public yesterday, per Neil's directive)
2. Any other events the user has access to (events created by the user or the user's org or where the user is a collaborator)

After writing that now, it's clear that I didn't have Admins in mind when I wrote that code, just generic users. Including the case for Admins will be a very quick and easy change. So in addition to the two cases above, I would first add a test to check the user's role, and if an admin return all events, otherwise use the criteria above.

**Comment by aaronstephenson** [comment]
@JChipault I just pushed this change to the test server, keep an eye on notifications and let me know how it goes.

Note that this change (9cdb156) affects both the 'ALL Events' standard notifications and the custom notifications.

**Comment by JChipault** [comment]
The test I set up yesterday sent the expected notifications overnight! I want to do one more round of overnight testing.

I did want to note that this statement "excluding those that changed from private to public yesterday, per Neil's directive" goes the other way too so maybe should read "excluding those that changed from private to public OR public to private yesterday, per Neil's directive". The test I did overnight seems to catch both scenarios (private to pubic OR public to private) but I wanted to just point out the wording to you in case it matters for documentation.

Thanks! I'll be back in touch after another round of checking but I'm optimistic that this is solved

**Comment by JChipault** [comment]
Second round of testing gave expected results. Looks good

**Comment by aaronstephenson** [comment]
Fix implemented in v2.0.14 6e77a39

**Comment by aaronstephenson** [comment]
@JChipault this is now live on the production server.
