### ISSUE TITLE
Possible data issue - Popular searches empty result

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#433]
Jenny pointed out there was an issue with popular searches showing a blank search. I confirmed that that is technically the accurate display of the data from the server:
![image](https://user-images.githubusercontent.com/6978380/102821965-aad5d900-439d-11eb-9b05-51d5e22ac86e.png)
In this case 'data' actually refers to the search composition itself, i.e. the search parameter and their values. You'll note the circled one is empty, hence the blank popular search (we never planned for an empty one). I realize this is very likely just the actual mathematical outcome of the logic in place since it is probably common for people to click 'Search' with no search parameters included. 

@nbaertlein Sending this to you first as the data steward. Any thoughts on how to handle this on your end, or shall we logically exclude the empty search, since its literally not a search at all? 
CC: @JChipault and @aaronstephenson

**Comment by JChipault** [comment]
@nbaertlein  Seeing the criteria for number affected in the popular searches on the front end is something that I thought we had fixed before, but then I noticed it wasn't working. However, saving a search that has the criteria of number affected IS working (github #1008). So perhaps you could re-load the saved searches into popular search and then the popular search would work?

**Comment by aaronstephenson** [comment]
I can fairly easily prevent the empty search from ever being saved as a popular search, let me know.

**Comment by nbaertlein** [comment]
I've fixed the data for popular searches so we don't have an empty search.  Not saving the affected count was an issue earlier, but it looks like it works fine now and I don't know how this one was reset.  I'll keep an eye on it moving forward.
@aaronstephenson This is low priority as these should not rise enough to be listed in popular searches, however if it's easy enough, please prevent these from being saved as you've suggested.  Thanks!

**Comment by aaronstephenson** [comment]
I just took a look in the [code](https://github.com/USGS-WiM/whispersservices/blob/master/whispersapi/views.py#L2709), and the empty searches should not be created at all.

I am testing for the length of the query_param list, and if it is zero then the search save code block is skipped. Looking in the various DBs, all of the occurrences of the "{}" have created and modified dates from 2019, with just one from 2020 (April, by the admin user).

So I think the problem here is just that there is some old junk data in the searches table, not that new empty searches are being saved or updated. Neil, you can delete those records with no side effects.

**Comment by aaronstephenson** [comment]
@nbaertlein how are things looking here? Can this issue be closed?

**Comment by nbaertlein** [comment]
@aaronstephenson Everything looks good on my end.
