### ISSUE TITLE
permission error message

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#442]
Ok, the collaborator thing for issue #426 might have been a red herring... I just received a report from a partner who got that same permission error that we were keying in on for #426 but he got it when he was trying to update end dates on events without any collaborators. The person trying to make these changes (Robb Kaler) is the event owner for all of these events, and the other thing that's puzzling here is that he was sometimes able to add end dates without getting the error message. See details below.

Here's what he reports -

Event 200582 
While adding “end date” for location 3 of event # 200582 (Shishmaref with 4 locations) received an error message: Error. Event location details not updated. Error message: {"detail":"You do not have permission to perform this action."}
Updated ‘end date’ for Locations 1,2 & 4.

Event 200595 
Received the same error message when I tried to update end date for location 1. Updated ‘end date’ for Location 2.

Event 200596 
Received the same error message when I tried to update end date for location 1.

Event 200844 
Updated location 1 end date.

**Comment by JChipault** [comment]
I think you'll see this report, but I'm tagging you just in case that's needed - @aaronstephenson

**Comment by aaronstephenson** [comment]
@JChipault I'll take a look.

I get automatic notifications for all issues and comments in this repo since I'm the maintainer. I disabled notifications on the client repo because while it was in active development there was no much activity there that didn't directly apply to me that it was filling up my inbox, so if you want me to see something in that repo just tag me. But for this one you don't need to.

**Comment by aaronstephenson** [comment]
In the case of Event 200582 Location 3, the event_location record was created by Barb Bodenstein (org 2). Robb is in org 1107, which has no parent org. It looks like in the permissions lookup in this case, the code is checking the ownership of the the event_location, not the parent event, and because the orgs don't align the code determined that Robb doesn't have edit permissions. So the fix here is to change the permissions lookup to reference the event and not the event_location (which was the original intent).

**Comment by JChipault** [comment]
I think we'd want the event owner to be able to read/write all locations but I'm double-checking with Neil on that to make sure I'm not overlooking something

**Comment by nbaertlein** [comment]
Yes.  That makes sense to me.  The event owner should have write permissions for anything in an event.

**Comment by aaronstephenson** [comment]
Fixed in 2.0.15 ec16d0d.

@JChipault I just pushed this fix to both prod and test servers. I also checked every case that Robb mentioned and they all work as expected now.

**Comment by nbaertlein** [comment]
Aaron,  I don't know if this is related, but seems it might.  We have a new bug on the live site.  I cannot not view any event details when logged in with a partner role (partner manager, partner admin, etc)  This included events that are within my org.  Example logged in as user nwhcPartnerManager (NWHC, partnermanager) and could not access event 200996.

**Comment by aaronstephenson** [comment]
@nbaertlein please create a new issue to record what you're seeing, and please include as many details as possible so I can better troubleshoot it. I am on leave today, and leaving the house for the day in 10 minutes, so for now I'll just revert the prod server to the previous version (2.0.14).

**Comment by aaronstephenson** [comment]
I decided to take a quick look anyway and found that it was an easy fix. New version pushed 2.0.16 c25c37b to prod and test.
