### ISSUE TITLE
Issues when logged in with a partner role (Partner User, Partner Manager, or Partner Admin)

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#443]
Seeing multiple issues when logged in with a partner role, but works fine when logged in as a public or WHISPers admin.  Tested in both test and production sites with the user 'nwhcPartnerManager'
1.  Cannot download event details report.  Download process gets stuck in loop when clicking 'Download Event Report'.  
2.  Cannot edit a species.  When clicking the 'Edit Species' button the pop-up box does not contain any data other than the species name.  Get an error message when trying to add/update any numbers that reads: "Error. Species not updated. Error message {“detail”:”Not found.”}"
3. Landownership is not displaying, despite being found in the tables

We've been getting a flurry of reports from various partners and we are continuing to test, so more partner role related issues may be forthcoming.

**Comment by aaronstephenson** [comment]
Can you give an example event ID so I can attempt to recreate what you're reporting?

1 Sounds like a front end issue. Using various random event IDs, I can download event details reports directly from the API. When I try using the client with the browser developer tools open, I see dozens of errors related to client actions, none due to the API.
2 and 3 sound like side effects of a change I made to serializers last time. Probably pretty simple.

**Comment by aaronstephenson** [comment]
Yup, 2 and 3 are definitely side effects of a recent change I made to a couple serializers. Fixed in 2.0.17 db3435c. Pushed to both prod and test servers.

1 is likely fixed by [2.16.2](https://github.com/USGS-WiM/whispers/releases/tag/v2.16.2) [1e6d9a0](https://github.com/USGS-WiM/whispers/commit/1e6d9a05bdc0c11c986b4c1b5247ffa97626972b) from the client repo.

**Comment by nbaertlein** [comment]
This caused another side affect.  I can no longer access publicly available events when logged in as a non-admin user (both test and production).  
Examples below.  Event example is a public event owned by Arizona.  Logged in access are by non-Arizona accounts.

Generic Access (not logged-in):
![image](https://user-images.githubusercontent.com/38669574/106015466-22291780-6084-11eb-958d-2955df6dc3e5.png)

Admin access:
![image](https://user-images.githubusercontent.com/38669574/106015502-29502580-6084-11eb-999f-c30f670a7ff5.png)

Non-Admin access (public, partner manager, & partner admin):
![image](https://user-images.githubusercontent.com/38669574/106016604-3d485700-6085-11eb-8b9e-81c1afe2cab8.png)
![image](https://user-images.githubusercontent.com/38669574/106015553-35d47e00-6084-11eb-839c-0775b962c4e9.png)
![image](https://user-images.githubusercontent.com/38669574/106015561-379e4180-6084-11eb-962a-41ec992b9b0e.png)

**Comment by nbaertlein** [comment]
One other scenario:  I CAN access from a partner account if its within the same organization.  Example here the event is owned by NWHC (Barb) and is accessed by a NWHC partner manager account:
![image](https://user-images.githubusercontent.com/38669574/106017142-c790bb00-6085-11eb-81b9-6ca55dd9ad53.png)

**Comment by aaronstephenson** [comment]
Apologies for that. I found the problem, a simple stupid error on my part, trying to look up a parent event value when the object is already an event: `'Event' object has no attribute 'event'` (I was assuming the object was an EventLocation).

BTW you should be able to see the error messages in the browser's developer console, which would help in future troubleshooting to more quickly identify the problem. (this works better in the test environment than in the prod environment, since test has `debug` set to True in Django and the error response is verbose, but prod has `debug` set to False, so the error response would be a generic 'Server Error')

![image](https://user-images.githubusercontent.com/8713712/106031149-85bb4100-6094-11eb-9b00-551c45a7a995.png)

**Comment by aaronstephenson** [comment]
Fixed in 2.0.18 326ba3a, pushed to test and prod.

**Comment by nbaertlein** [comment]
Looks like I have access now.  Thanks @aaronstephenson for that and the tip on the console.

**Comment by JChipault** [comment]
I just got the {“detail”:”Not found.”}" error message when deleting a species diagnosis while in my jchipault (whispers admin) account. I got the {“detail”:”Not found.”}" toast message but simultaneously got the middle-of-the screen message with white background that told me that it was successfully removed. The diagnosis did get removed from the display. This was deletion of the diagnosis of chronic wasting disease from event 200933. I didn't react fast enough to get a screen shot or hit F12. I tried to repeat the issue by deleting "emaciation (NOS)" but that deleted without a hitch. Maybe this is nothing?? A blip in my internet connection, perhaps, which causes the toast message? But wanted to report here in case it means something deeper.

**Comment by aaronstephenson** [comment]
Yeah, it sounds like a network blip... like the DELETE succeeded, then the client tried to do a GET for the same record but was told it no longer exists ("Not found."). Keep an eye out for weirdness like this and let us know if you see it happen again. Thanks!
