### ISSUE TITLE
Event saved with no data

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#458]
Barb Bodenstein created event 201146 around 7a-7:10a this morning and she was able to save the event and everything seemed ok (i.e., she doesn't remember seeing any error messages), but when she realized that the service request email did not arrive at nwhc-epi@usgs.gov, she went to look at the event and found that it was basically a shell without any data. I took screen shots of the empty event; Barb has since gone in to the event details page and edited this event because it was connected to carcasses coming to our lab soon so she wanted the record accurate.  This saving of an empty event obviously violates a bundle of business rules. 

She had a couple of thoughts...
1) she's out in Arena, WI and her internet is spotty (many of our field biologist partners have bad internet too)
2) she thinks USGS tends to push updates around 7a so she wonders if that happened right as she was submitting data?

She created 201147 about 5 minutes after creating 201146 and 201147 looks fine.

Any thoughts regarding this blip?

![image](https://user-images.githubusercontent.com/49287076/109974088-cffc9700-7cbe-11eb-86d8-37f5e473ad2e.png)
![image](https://user-images.githubusercontent.com/49287076/109974105-d428b480-7cbe-11eb-989b-3cdd4be9876b.png)
![image](https://user-images.githubusercontent.com/49287076/109974118-d7bc3b80-7cbe-11eb-9a02-8c95339c1d15.png)

**Comment by JChipault** [comment]
Jasper County and this screen shot has the other info for that location
![image](https://user-images.githubusercontent.com/49287076/110135408-1a9c1300-7d94-11eb-8fa9-d202a0d33f96.png)

**Comment by JChipault** [comment]
Thanks for looking into this.

**Comment by aaronstephenson** [comment]
@JChipault I can't find anything wrong in the code. I've tried creating new events with the exact event location information as shown in your screen capture, but the event creation succeeds with all details correct. My only explanation is that something went wrong in the request to the FWS API that one time that Barb tried yesterday morning, maybe the FWS server was down momentarily or a packet got lost in transit.

To protect against a problem like that, I wrote some code to wrap all calls to third party services in try:except blocks, and if an exception is raised, the app emails the admin team with the exception and then continues on with the event create process, since Flyways are not an essential attribute and can be ignored.

Let me know when you're comfortable having me deploy this change to the production server.

**Comment by JChipault** [comment]
I talked with Neil and we're cool with this approach. Should this sort of "bail if it's not working" approach be used for any other third party services that are pinged during create event? GNIS? Not necessarily anything that has to be done right now but wanted to check in with you on that while your mind is on this topic.

**Comment by JChipault** [comment]
Just re-read your Friday message... maybe you've already taken care of all third party pings since you said "wrap all calls to third party services in try:except blocks"

**Comment by aaronstephenson** [comment]
Right now, the GNIS lookup happens only in the client app (the API just passes the value submitted by the user thru to the DB). The API only uses 2 third party apps, namely FWS Flyways (for EventLocation.flyways) and Geonames (for looking up country and/or state and/or county when the user doesn't include those fields but did include lat+lng), and on Friday I wrapped all those calls in try:except blocks.

The nice thing here is that since flways isn't a required field, and so long as the user submitted lat+lng (already being validated) then country+state+county aren't required fields either, then this "bail if it's not working (and email admins about what happened)" is a workable solution.

I can deploy this update to both test and prod (or just one) as soon as you're ready.

**Comment by JChipault** [comment]
That brought up something new to me... I didn't realize that the business rule for "if you have a lat+lng then you don't need country+state+county" was active. Working through the front end, I can't clear out country and I can't click the "save event" button unless I have state+county. Screen shot of what it looks like if I have a lat+lng and try to get away with not having state+county:

![image](https://user-images.githubusercontent.com/49287076/110382931-35cf8280-8021-11eb-9e15-676efd938bb1.png)

But I like that that rule is there in the backend even if it's not available to me as a frontend user yet, so maybe we just keep your try:except block in place and make a note that we should consider tweaking the front end to allow a user to attempt to save an event if they have lat+lng but not country+state+county.

@nbaertlein - what do you think?

**Comment by aaronstephenson** [comment]
I chatted with Neil today, he gave me the green light to deploy the fix.

Fix implemented in 2.0.19 dc50f66 and pushed to both test and prod servers.

**Comment by JChipault** [comment]
@aaronstephenson  @nbaertlein  New issue that I think is related: can't save events with lat/longs now.

Got message from partner Nancy Businga at 845a about how she couldn't save an event on the live site. She got this message when she tried to save:
![image](https://user-images.githubusercontent.com/49287076/110978681-4cc7ea80-8329-11eb-98cf-e71569a90138.png)

I told her to try removing the lat/long and then she was able to save (event 201158). I then went into the event details page and was able to add the lat/long in via that route.


I just tried using the test site at 1145a to enter the same event info that Nancy had entered into the live site. Using my jchipault account, this is what I saw.
![image](https://user-images.githubusercontent.com/49287076/110979515-4e45e280-832a-11eb-9e1e-a8452ac4d830.png)


Hit save event again and hit F12 this time and saw:
![image](https://user-images.githubusercontent.com/49287076/110979145-d7a8e500-8329-11eb-901e-f284a2378676.png)

Copied this:
Form Status: VALID

 {
  "event_reference": "2115",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": null,
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [],
  "new_service_request": {
    "request_type": 0,
    "new_comments": []
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "Norwak",
      "start_date": "2021-03-09",
      "end_date": "2021-03-09",
      "country": "30",
      "administrative_level_one": 51,
      "administrative_level_two": 3084,
      "latitude": "43.775252",
      "longitude": "-90.575921",
      "land_ownership": "6",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "yard",
      "history": "found dead",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 181,
          "population_count": null,
          "sick_count": null,
          "dead_count": 1,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
} 



Removed lat/long. Hit "save event" again. Blue loading line moved for almost a full minute. Then got event saved message (170992).

**Comment by aaronstephenson** [comment]
Ugh. So the validator as written was looking up the county (as found by reverse geocoding the lat/lng) using just the county name. There are currently 17 Monroe Counties in the table, and the first occurrence was being returned (from Alabama), which of course didn't match the lat/lng that was submitted (Wisconsin). I'll need to improve the validation to use both county name and state name. Fix coming shortly.

**Comment by aaronstephenson** [comment]
Fix implemented in v2.0.20 53bf1a5 and pushed to both test and prod servers.

@JChipault thanks for the thorough bug report on this, it was a huge help. When I was testing my code when I originally wrote these validations I had just been using Dane County as the location, and since there's only one of those in the DB table this scenario never came up for me. I should have used a more popular location name!

**Comment by JChipault** [comment]
@aaronstephenson Thanks for the quick fix!  So since I was able to add the lat/long into this event from the event details page, is it not checking that a lat/long is within the county in that setting? Or is it that the code is checking the right county-state combo from the event details page? If the former, not sure it's something to spend time fixing, but I'm just trying to figure out what our present situation is.

**Comment by aaronstephenson** [comment]
Right now it's only doing that validation on event creates, not updates.

**Comment by JChipault** [comment]
@nbaertlein - are you ok just adding extending this validation to the edit event page to the wish list for future development?

**Comment by nbaertlein** [comment]
@JChipault Yes.  Let's add this to the next development effort.  As I mentioned to Blake and Aaron in a chat, I think we could leverage this bit of code for new functionalities.  
Thanks for tackling Aaron.
