### ISSUE TITLE
Remove inactive users from receiving notifications and from collaborator options dropdown

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#504]
**Describe the bug**
We noticed that a partner admin with an inactive account (Bob Dittmar, who passed away) was getting emails about user requests in his organization even though his account is inactive. Can we make is so that inactive accounts do not get any notifications at all?

Inactive users are also still available on the collaborator dropdown list (see screenshot) and shouldn't be. Can we remove inactive accounts from the collaborator options?

![image](https://user-images.githubusercontent.com/49287076/129581777-77dd5921-a233-4002-9248-97be2ed9df72.png)

**Comment by BlakeDraper** [comment]
@aaronstephenson this notifications issue applies to the backend code, as does the email lookup, via the `/users/verify_email/` endpoint.

**Comment by aaronstephenson** [comment]
This is changed in branch 504 (4d84674c). I will deploy it when I have resolve a few more issues and can bundle them together.

One question tho @JChipault: what should be done when the _only_ notification and/or email recipient is inactive? For example, when a Service Request is created, but the event creator (the sole recipient aside from the person who created the SR) is inactive? The SR would then presumably go unnoticed unless the DBA comes across it, or the SR creator finds a way to contact the admins.

**Comment by JChipault** [comment]
In addition to the event creator, SR also get sent to nwhc-epi@usgs.gov though, right?

**Comment by JChipault** [comment]
Though it could apply to the Service Request Response. If the event owner and the person who made the request are the same and that one person is inactive... signing off for the day now but will puzzle over this more tomorrow

**Comment by aaronstephenson** [comment]
Yes, sorry, I mean Service Request Response.

It's not a situation where the SR creator and the Event owner are the same person, which wouldn't work because an inactive user can't log in to create the SR. I just mean when the Event owner is inactive. Perhaps it's a long-running event, or one that hasn't been updated in a while, and the Event owner has retired or left the job where they used WHISPers, and never transferred the Event to someone else. The business rule for Service Request Response lists the recipients as "user who made the request, event owner".

But maybe forget about this, It's probably an edge case and I'm just overthinking it.

**Comment by JChipault** [comment]
Yea, I think that's an edge case, but I'll make note of it in our "wish list" to maybe circle back to in the future if it starts to feel problematic. For now, I'm ok letting it ride as is.

This did prompt me to think about how this change might affect the collaborator alert feature though... let's say Bob Smith is added as a collaborator on an event when his account was active, then he changed jobs and his account was inactivated, then the event owner goes to send out a collaborator alert... could Bob Smith (who is now inactive) also be removed from the possibilities for recipients of a collaborator alert? That way the event owner doesn't think they are sending something to Bob when actually they aren't

**Comment by aaronstephenson** [comment]
>could Bob Smith (who is now inactive) also be removed from the possibilities for recipients of a collaborator alert?

Yes, I can implement that right now, it's a simple change. I am imagining this to just be a silent removal... unless you want the event owner notified that Bob has been automatically removed because his account is now inactive?

**Comment by JChipault** [comment]
Good point... I was imagining a silent removal... but that could be confusing for the user because I'm assuming that Bob Smith would still be listed as a collaborator in the read vs read/write section (because maybe he did contribute to the event in the past) so does that leave the event owner wondering why Bob Smith isn't an option in the collaborator alert interface? Possibly. How hard would it be to give the user an explanation if they are using the collaborator alert feature for an event that has a now inactive collaborator?

**Comment by aaronstephenson** [comment]
I think the easiest way to notify the event owner is just a notification and/or email at the time that Bob is made inactive, saying that Bob is now inactive and will no longer receive notifications and will no longer be addable as a collaborator. Otherwise, something like a message on the collaborator alert interface would require a subsystem to manage those kinds of messages for that interface plus changes to the client app to check for and show those kinds of messages.

**Comment by JChipault** [comment]
ah, ok... thanks for explaining... let's just do a silent removal for now then and I'll put thinking about how to notify people about that on our "wish list" for the future.

**Comment by aaronstephenson** [comment]
Feature added in v2.1.7 (9f5eb70) and published to the test and production environment.

**Comment by JChipault** [comment]
Hi Aaron, looks like inactive user Nathan Kudla (user id 137) is still getting notifications.  Based on the 9/21/2021 fix date above, 24 "update needed" notifications have been sent to Nathan since then, and no others. Maybe this specific notification was left off the list of those not to send to inactive users?

![image](https://user-images.githubusercontent.com/49287076/148412754-64754523-b3be-4733-8060-ea566673e5ce.png)

Neil's code that he used to investigate:
select a.id, a.created_date, source, b.email as recipient, b.organization_id, b.is_active,
a.subject, a.body
from public.whispershistory_notification a
inner join (select * from public.whispers_user where is_active = false) b on a.recipient_id = b.id
inner join (select id, min(history_date) as change_date
from public.whispershistory_user
where is_active = false
group by id) c on b.id = c.id
where a.history_type = '+'
and c.change_date < a.created_date
order by a.id desc;

**Comment by aaronstephenson** [comment]
>Maybe this specific notification was left off the list of those not to send to inactive users?

Right you are! That earlier fix I only applied to standard and custom notifications, but I completely overlooked the stale event notifications. The recipients for those are supposed to be the general Epi user and the even owner, so I'll just check if the event owner is active, and if not only generate a notification for the Epi user.

Fixed in 8d8da299 but not yet deployed. I will include it in an update to the Test environment once I fix another open issue and can bundle them.

**Comment by aaronstephenson** [comment]
Pushed to test environment. @JChipault take a look and let me know if and when to push to production.

**Comment by JChipault** [comment]
Hmmm... wondering if any other notifications need to be turned off for inactive users. We started this ticket by asking if user account request notifications could get turned off for inactive users ("We noticed that a partner admin with an inactive account (Bob Dittmar, who passed away) was getting emails about user requests in his organization even though his account is inactive. Can we make is so that inactive accounts do not get any notifications at all?"), and we've talked about the suite of service request notifications and alert collaborator and not being able to add an inactive user as a collaborator to begin with and custom/standard and now updated needed... what about 1) high impact disease notifications and 2) collaboration requests (where a user sees an event that they want to request to be a collaborator on) - are those off for inactive users?

**Comment by JChipault** [comment]
PS - I'll make a note for future development to consider the scenario for how the org admins and org managers who get the collaboration request email would know that the event owner is inactive and thus unable to grant collaborator access. This is an edge case so probably not worth working through right now.

**Comment by aaronstephenson** [comment]
I looked thru the source code at each notification, here's what I found:

1.  [High Impact Diseases](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/models.py#L1592), recipients: WHISPers admin team, WHISPers Epi staff, event owner; checking for inactive user ✅ 
2.  [User Change Request](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/serializers.py#L4506), recipients: WHISPers admin team, Admins of organization requested; checking for inactive user ✅ 
3.  [User Change Request Response Pending](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/serializers.py#L4527), recipients: user; not checking for inactive user ❌ 
4.  [User Change Request Response Yes](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/serializers.py#L4595), recipients: user, WHISPers admin team; checking for inactive user ✅ 
5.  [User Change Request Response No](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/serializers.py#L4612), recipients: user, WHISPers admin team;recipients: users with this notification configured
6.  [New Lookup Item Request](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/views.py#L155), recipients: WHISPers admin team; checking for inactive user ✅ 
7.  [Collaboration Request](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/views.py#L393), recipients: event owner, org manager, org admin; checking for inactive user ✅ 
8.  [Collaborator Added](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/models.py#L2573) (Read), recipients: user(s) added as collaborator; not checking for inactive user ❌ 
9.  [Collaborator Added](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/models.py#L2658) (Write), recipients: user(s) added as collaborator; not checking for inactive user ❌ 
10. [Alert Collaborator](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/views.py#L324), recipients: user(s) chosen from among the collaborator list;  checking for inactive user ✅ 
11. [Service Request](https://github.com/USGS-WiM/whispersservices/blob/master/whispersapi/serializers.py#L3709), recipients: nwhc-epi@usgs.gov or HFS dropbox; not checking for inactive user (epi user is a dropbox) ➖  
12. [Service Request Response](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/models.py#L1844), recipients: user who made the request, event owner; not checking for inactive user ❌ 
13. [Service Request Comment](https://github.com/USGS-WiM/whispersservices/blob/master/whispersapi/serializers.py#L489), recipients: toggles between nwhc-epi@usgs or HFS AND user who made the request and event owner;  not checking for inactive user (epi user is a dropbox) ➖ 
14. [Standard Notifications](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/scheduled_tasks.py#L950), recipients: users with this notification configured; checking for inactive user ✅ 
15. [Stale Events](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/scheduled_tasks.py#L1016), recipients: event owner and Epi staff;  checking for inactive user ✅  (also, epi user is a dropbox)
16. [Quality Check](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/models.py#L396), recipients: Epi staff; not checking for inactive user (epi user is a dropbox) ➖ 
17. [User Created](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/views.py#L2224), recipients: user, WHISPers admin team; checking for inactive user ✅ 
18. [Custom Notifications](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/scheduled_tasks.py#L1423), recipients: users with this notification configured; checking for inactive user ✅ 
19. [User Email Verification](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/serializers.py#L4243), recipients: user; not checking for inactive user ❌ 
20. [Password Reset](https://github.com/USGS-WiM/whispersservices/blob/918d2cfa1c00dc3b39f2141c5c2d7cfbf0d4fb02/whispersapi/views.py#L2155), recipients: user; not checking for inactive user ❌ 

In summary...

- About half are checking for inactive users
- several go to the epi dropbox which is always active and so are not checked
- User Email Verification and Password Reset must be sent regardless of active status
- User Change Request Response Pending is not checked for inactive user because it gets created immediately when that same user creates the User Change Request.
- Collaborator Added should definitely be checked, and I said in this very issue thread months ago that I fixed it but it must have slipped my mind while working on similar things, so I'll fix that right away.
- Service Request Response and Service Request Comment are not checked for inactive user because I assumed they would be timely responses, but I can see now that some might sit for a while and the user might become inactive in that time.

Let me know what your thoughts are on these @JChipault, in the meantime I will implement a check for Collaborator Added right now.

**Comment by aaronstephenson** [comment]
Collaborator Added notifications fixed in 791ebca9 and pushed to test environment.

**Comment by JChipault** [comment]
Thank you for this list! Super helpful!

I think you had already accounted for the Collaborator Added notification by removing inactive users from the collaborator list drop down on the front end, right? Regardless, looks like we're in good shape on that front.

I think it would be good to check for inactive users on service request response and service request comment. For both of those they'd have to log in to see the response or comment and if they are inactive they won't be able to log in. I'll make a note in our future development wish list that we'd probably want something here to notify the person who is making the comment or response that their intended recipient is inactive. Again, this is probably an edge case though so I'm not too concerned.

**Comment by aaronstephenson** [comment]
Fix deployed in test and production environments as v2.1.11 0e85d7f

**Comment by JChipault** [comment]
@aaronstephenson - did you add in these checks from my 1/19 comment: "I think it would be good to check for inactive users on service request response and service request comment"?

**Comment by aaronstephenson** [comment]
No, you mentioned future development and edge case and it seemed to me that that encompassed everything in that paragraph, so I let it be. Implementing it would only take a few minutes, if you want me to do that now.

**Comment by JChipault** [comment]
Sorry, my wording was confusing. I was indicating that we don't need to figure out front end messaging to users on why someone isn't getting service request emails right now (can punt that), but I would like to turn off email notifications to inactive users for service request response and service request comment so that inactive users aren't receiving emails that they can't do anything with

**Comment by aaronstephenson** [comment]
Implemented in v2.1.12 6474df5 and pushed to both the test and production environments.
