### ISSUE TITLE
Remove other partners' circles of trust from NWHC dashboard

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#506]
**Undesired Design or Confusing behavior**
NWHC users are able to see everyone's circles in their dashboard. (actually, maybe it's the WHISPers Admin role? and those just happen to all be NWHC people?... but I think we checked that and it was all NWHC users)

**If Possible, Describe a Solution**
Want to only see circles that have been created within your own organization when looking in your dashboard (same goes for contacts, but I believe that is functioning as we want it to)

**Comment by aaronstephenson** [comment]
@JChipault The way this is written is that Anonymous (Public) users can't see any circles, SuperAdmins and Admins can see all circles, and everyone else can see the circles in their org.

Do you want me to change this so that SuperAdmins and Admins only see circles from the own org, or some kind of option to see either all circles or just circles from their own org (like with the `/eventsummaries/` endpoint which has a `/user_events/` sub-endpoint (the former returning all event summaries and the latter returning only event summaries belonging to the user/org/collaborators))?

**Comment by JChipault** [comment]
Change so that SuperAdmins and Admins only see circles from their own org, please.

Thanks!

**Comment by aaronstephenson** [comment]
Feature added in v2.1.7 (9f5eb70) and published to the test and production environment.
