### ISSUE TITLE
standard and custom notifications not being emailed out

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#513]
A partner from Wisconsin DNR pointed out that she's no longer getting emails based on her pre-set notifications. I perused my email and looks like the last custom or standard notification that I received from the live site was on 8/18. 

Neil looked and could see that the notifications are being created but not emailed.

Is there a way we can prevent these notifications from going dark without us knowing?

**Comment by aaronstephenson** [comment]
I looked at the notifications table, and it appears that all the records since 8/18 are of the "immediate" variety (that is, the notification and email are created and sent immediately, like collaborator requests), rather than the "scheduled" variety (the nightly custom and standard notifications). So I don't think it's that emails aren't being sent, I think the problem is that the scheduled tasks just aren't being triggered.

So, I just restarted the `celeryd` and `celerybeat` daemons, and the celery logs are now filled with tasks with today's date. So it seems the daemons just stopped working, despite both having `active` statuses when I checked before I restarted them. Let me know tomorrow if you **don't** receive expected notifications tomorrow.

Re: preventing this, I'm not sure. This seems to be a system-level (as opposed to app-level) problem. We could have a cron job that restarts the daemons every morning before the notification tasks are set to run, but that's awfully "brute force" for my taste, plus I suspect it would make the notification processes run twice (once on the restart and again at the scheduled times).

Alternately, we could have a "health check" notification (maybe just turning on a standard ("All new/modified events"?) and a custom notification for the Admin user) that runs daily and that we know should always create a new email, and we could have a script outside the app also run daily via the system cron to check if that notification was created as expected (i.e., is present in the email inbox), and if not send an email to the NWHC admin team. Just brainstorming.

**Comment by JChipault** [comment]
@aaronstephenson Looks like we went dark again around 10/19. I touched base with Ali and he doesn't have any more input on this that he hasn't already shared via email. I'm open, but think it would be good to have some way to prevent these from silently going dark.

**Comment by JChipault** [comment]
@aaronstephenson any chance we could at least get a re-start on these notifications soon, even if we put off the long-term solution for how to keep them from shutting down?

**Comment by aaronstephenson** [comment]
@JChipault I restarted all three daemons (httpd, celeryd, celerybeat) on both the test and production servers. Both Neil and Tom can do this at any time, they have the same privileges on those servers as me.

As for a longer-term solution, my project manager says the next team (NWHC-WIM) check-in is next Thursday and they will discuss it then.
