### ISSUE TITLE
QC needed email not issued during Create Event

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#514]
Seems that no "Quality Check Needed" notification email is going out if the "process status" field is set to "quality check needed" during Create Event. (seems to work fine from the Event Details Page)

Was first alerted about this based on not receiving a QC needed email for event 201477 on the live site.

To further test, on 9/14/21 I created 171052 on the test site and received no QC needed email; however, I edited event 171046 and set it to "quality check needed" and DID receive an email.

Want an email sent from the Create Event page just like it is from the Event Detail page

**Comment by aaronstephenson** [comment]
The code that processes the "Quality Check Needed" notification is on the Event model, which is independent of the code that handles the branching "create" and "update" use cases. In other words, the "Quality Check Needed" notification code runs every time an event is saved, regardless of whether the event was just created or updated.

Additionally, that "Quality Check Needed" notification code block has a test to ensure that no notification is created if the current user-assigned event status is the same as the event's previous status; I don't remember the decision around this, but I think it was something to do with not wanting more than one of this kind of email per event per day. In other words, if someone sets the event status to "Quality Check Needed" in the morning and then updates the event later in the day but the event status is still "Quality Check Needed", you don't want another notification to go out.

I don't think this particular use case (setting the event status to "Quality Check Needed" and event complete to True at the time of event creation) was anticipated when we were developing the app. In the code, when an event is created there is no previous event status, so the code just assigns the new event status in that case, which results in the previous and current statuses being the same and thus skipping the notification creation code. I can certainly change it to allow for this use case, though.

**Comment by aaronstephenson** [comment]
@JChipault This feature was added in 5b62dbe and is now available on the test server.

**Comment by JChipault** [comment]
I created two events on the test site that were marked as "quality check needed" (one complete  (171054) and one incomplete (171053)) and also edited a pre-existing event (171048) to be "quality check needed" and have not received any email notifications about any of them in the past half hour since I did the creating/editing. I was expecting 3 emails.

**Comment by aaronstephenson** [comment]
@JChipault can you send me the JSON that the client app generates for these? Debugging the API goes so much faster when I don't have to use the client to create an event and wrack my brain to get all the details correct; you know the subject matter better and can create an event with the exact criteria much faster than I can.

**Comment by JChipault** [comment]
I'm actually wondering if it's something that needs to be reset with regard to notifications being issued/emailed. I say this because on 9/14/21 [quoted from earlier in this ticket string] "I edited event 171046 and set it to "quality check needed" and DID receive an email." So today I edited 171048 in a similar way, kind of as a control, assuming that I'd surely get that email since that was working on 9/14 but none of these scenarios sent an email out.

**Comment by JChipault** [comment]
Also, I think these notifications are instant (not overnight), correct? I think we talked about making them overnight at some point (which might explain why some of your code is written for that) but I took a look back at the time stamps for previous Quality Check notifications and they were coming in throughout the workday

**Comment by aaronstephenson** [comment]
Thanks for the JSON, that'll help me troubleshoot much faster.

Take a look at the source code here and tell me if anything isn't right:
https://github.com/USGS-WiM/whispersservices/blob/test/whispersapi/models.py#L353

That code runs on every event save (all creates and all updates) no matter what.

The deciding logic for the "Quality Check Needed" notification is essentially this:
```
if (self.event_status.name == 'Quality Check Needed'
                and (is_new or self.event_status.id != self.__original_event_status.id)):
```

**Comment by aaronstephenson** [comment]
Yes, the notification and email are instant; the way the code is written is just to guard against multiple notifications for the same thing, not because it was intended for nightly runs.

I just used your example JSON locally and everything worked as expected, and the notification record was created and the email was sent. So this appears to be a problem with the server, not the code. I'll look into that.

**Comment by aaronstephenson** [comment]
I looked at all the celery logs and rabbitmq queues on the test server from today, and here's what I saw:

At 10:03:55 an email was sent to user 'nwhc-epi' with subject 'TEST. TEST. Quality Check: Event 171053'.

At 10:05:12 an email was sent to user 'nwhc-epi' with subject 'TEST. TEST. Quality Check: Event 171054'.

At 10:07:56 an email was sent to user 'nwhc-epi' with subject 'TEST. TEST. Quality Check: Event 171048'.

At 11:46:51 an email was sent to user 'nwhc-epi' with subject 'TEST. TEST. Quality Check: Event 171055'.

Events 171053, 171054, and 171055 were newly created with event status of 'Quality Check Needed', and event 171054 was edited with a change of status from 'New Event Record' to 'Quality Check Needed', and each of those triggered a notification and email.

As a final check, I created a new event (ID 171056) with complete=True and event_status="Quality Check Needed", and I recieved both a notification and an email (I made a temporary change in the code on the test server to send all notifications and emails to me instead of the epis/admins, for the duration of my check). I then changed complete to False and event_status to "New Event Record", which of course did not trigger any notifications or emails. Lastly I changed complete to True and event_status to "Quality Check Needed", and I recieved both a notification and an email once again. I then changed the code on the test server back so that notifications and emails go to the intended recipients once again (instead of me). For what it's worth, I did all these steps for this check using the API directly (not the client app).

I also created one last event (ID 171057) just to ensure that the epis/admins were receiving notificaions and emails (and not me), and I saw the notification in the DB table as well as the email in the log file.

So from my investigations and checks, it seems that this issue is resolved and the code is working as intended as of my fix yesterday. Please let me know if I'm overlooking anything here.

**Comment by aaronstephenson** [comment]
Feature added in v2.1.7 (9f5eb70) and published to the test and production environment.

**Comment by JChipault** [comment]
Got it. Sorry for the wild goose chase yesterday : (  Issue was on my end had to do with the order of the "Rules" set up in the nwhc-epi@usgs.gov Outlook account. I see all those emails that generated yesterday morning now.
