### ISSUE TITLE
Add 'public' field with eventsummaries response for roles above Public

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#521]
Background on this issue: https://github.com/USGS-WiM/whispers/issues/740#issuecomment-949987815

**Comment by aaronstephenson** [comment]
@BlakeDraper I tested every user Neil mentioned (locally, so I could change the passwords so I could actually authenticate), and I saw the `public` field in the response for every request (using the web client, the browsable API, and Insomnia).

Ohhhhh, I see what's happening. On the main page, you're using 'id' as a query param to request an event summary. The serializer is expecting a primary key value from the URL path, not the query params (that is, .../eventsummaries/201551, not .../eventsummaries/?id=201551), similar to event details. I'm going to have to completely rewrite the init submethod for this serializer to accommodate that query.

This will really complicate things, though, because otherwise we'll be potentially mixing and matching field lists: for events the user has full permission to view, they will see all the fields, but for any other events they're only get the truncated list "public" fields, which could quickly lead to complications for any end user. I think what I'll need to do is just abandon testing the user's permissions based on event owner+org+collaborator, and just base it solely on role.

---

Just a bit of background in case it's useful:

The `public` field should already be available to anyone who has permission to view an event. There are three 'tiers' of field lists for event summaries: public, private, and admin. Which tier the user sees is determined in the serializer [init code block](https://github.com/USGS-WiM/whispersservices/blob/master/whispersapi/serializers.py#L5205). 

Essentially, here's how they're currently determined:

- Admin fields: SuperAdmins and Admins
- Private fields: event owner, or user who is in the event owner's org or parent org, or user who is an event collaborator (read and write); note that role doesn't have any bearing here
- Public fields: everyone else

**Comment by aaronstephenson** [comment]
Fixed in b87de6ee and pushed to test environment.

**Comment by BlakeDraper** [comment]
Tested on the test server and looks good. @JChipault did you want to test this yourself before we push to production?

**Comment by JChipault** [comment]
Looks good!

**Comment by aaronstephenson** [comment]
Pushed to production as v2.1.9 5fd774e.
