### ISSUE TITLE
Add 'active' Field to Organization

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/whispersservices#577]
Needs to be available in the API. It was already manually added to the DB table, so we'll need to do a bit of manual data manipulation.

**Comment by nbaertlein** [comment]
From Matt:
Would it be possible to add "active" to the OrganizationSlimSerializer (serializers.py) and OrganizationFilter (filters.py)? I only ask because the current "getOrganizations" endpoint on the front end uses "no_page&slim" and I would like to use "?no_page&slim&active=True".

If not, I can just have an endpoint use "?no_page", then filter the active orgs on the front end.

**Comment by aaronstephenson** [comment]
Absolutely! I can get that done shortly.

**Comment by aaronstephenson** [comment]
Implemented in 0616a964. Pushed to test and prod servers. Let me know if there's anything else!

**Comment by nbaertlein** [comment]
Will do.  Thank you.
